apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server
spec:
  replicas: 4
  selector:
    matchLabels:
      app: go-server
  template:
    metadata:
      labels:
        app: go-server
    spec:
      containers:
      - name: go-server
        image: go-k8s-demo:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: go-server-service
spec:
  type: NodePort
  selector:
    app: go-server
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080
    # nodePort removed because Service is now ClusterIP

---
# Ingress to expose the service on port 80
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-server-ingress
  annotations:
    # Use the ingress class that's available in your cluster, e.g. nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: go-server-service
            port:
              number: 80
